Repository googleapis/java-billingbudgets, pull requests merged in 2020-09, with the labels that each got.

#233 chore: regenerate README
  README.md
  synth.metadata
Labels: api: billingbudgets, cla: yes, context: none

#237 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#249 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#250 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#251 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: billingbudgets, automerge, cla: yes

#256 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#258 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
