Repository googleapis/java-billingbudgets, pull requests merged in 2020-10, with the labels that each got.

#261 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#263 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#266 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#269 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#270 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#273 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#275 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#272 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#279 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#280 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#282 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#285 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#283 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#287 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#288 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#290 feat: add v1 client library
  google-cloud-billingbudgets-bom/pom.xml
  google-cloud-billingbudgets/pom.xml
  google-cloud-billingbudgets/src/main/java/com/google/cloud/billing/budgets/v1/BudgetServiceClient.java
  google-cloud-billingbudgets/src/main/java/com/google/cloud/billing/budgets/v1/BudgetServiceSettings.java
  google-cloud-billingbudgets/src/main/java/com/google/cloud/billing/budgets/v1/package-info.java
  google-cloud-billingbudgets/src/main/java/com/google/cloud/billing/budgets/v1/stub/BudgetServiceStub.java
  google-cloud-billingbudgets/src/main/java/com/google/cloud/billing/budgets/v1/stub/BudgetServiceStubSettings.java
  google-cloud-billingbudgets/src/main/java/com/google/cloud/billing/budgets/v1/stub/GrpcBudgetServiceCallableFactory.java
  google-cloud-billingbudgets/src/main/java/com/google/cloud/billing/budgets/v1/stub/GrpcBudgetServiceStub.java
  google-cloud-billingbudgets/src/test/java/com/google/cloud/billing/budgets/v1/BudgetServiceClientTest.java
  google-cloud-billingbudgets/src/test/java/com/google/cloud/billing/budgets/v1/MockBudgetService.java
  google-cloud-billingbudgets/src/test/java/com/google/cloud/billing/budgets/v1/MockBudgetServiceImpl.java
  grpc-google-cloud-billingbudgets-v1/pom.xml
  grpc-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/BudgetServiceGrpc.java
  pom.xml
  proto-google-cloud-billingbudgets-v1/clirr-ignored-differences.xml
  proto-google-cloud-billingbudgets-v1/pom.xml
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/BillingAccountName.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/Budget.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/BudgetAmount.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/BudgetAmountOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/BudgetModelProto.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/BudgetName.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/BudgetOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/BudgetServiceProto.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/CreateBudgetRequest.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/CreateBudgetRequestOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/DeleteBudgetRequest.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/DeleteBudgetRequestOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/Filter.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/FilterOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/GetBudgetRequest.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/GetBudgetRequestOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/LastPeriodAmount.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/LastPeriodAmountOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/ListBudgetsRequest.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/ListBudgetsRequestOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/ListBudgetsResponse.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/ListBudgetsResponseOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/NotificationsRule.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/NotificationsRuleOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/ThresholdRule.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/ThresholdRuleOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/UpdateBudgetRequest.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/UpdateBudgetRequestOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/proto/google/cloud/billing/budgets/v1/budget_model.proto
  proto-google-cloud-billingbudgets-v1/src/main/proto/google/cloud/billing/budgets/v1/budget_service.proto
  synth.metadata
  synth.py
  versions.txt
Labels: cla: yes

#292 feat(v1beta1): add support for credit type filter field
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/AllUpdatesRule.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/AllUpdatesRuleOrBuilder.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/BudgetModel.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/Filter.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/FilterOrBuilder.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/proto/google/cloud/billing/budgets/v1beta1/budget_model.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#295 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#296 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#297 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#299 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
