Repository googleapis/java-billingbudgets, pull requests merged in 2020-11, with the labels that each got.

#305 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#306 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#308 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#309 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#311 docs: Reworded comments for the new credit types filter
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/Filter.java
  proto-google-cloud-billingbudgets-v1/src/main/java/com/google/cloud/billing/budgets/v1/FilterOrBuilder.java
  proto-google-cloud-billingbudgets-v1/src/main/proto/google/cloud/billing/budgets/v1/budget_model.proto
  synth.metadata
Labels: api: billingbudgets, cla: yes, context: full

#313 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#315 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#314 docs: Reworded comments for the new credit types filter
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/Filter.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/FilterOrBuilder.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/proto/google/cloud/billing/budgets/v1beta1/budget_model.proto
  synth.metadata
Labels: api: billingbudgets, cla: yes, context: full

#319 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#323 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#324 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#322 feat: promote to 1.0.0
  .repo-metadata.json
Labels: api: billingbudgets, cla: yes

#325 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#330 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#333 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#331 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#335 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#336 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#337 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full, samples
