Repository googleapis/java-billingbudgets, pull requests merged in 2020-06, with the labels that each got.

#164 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#159 feat(v1beta1): add subaccounts, labels to Filter
  google-cloud-billingbudgets/src/main/java/com/google/cloud/billing/budgets/v1beta1/BudgetServiceClient.java
  grpc-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/BudgetServiceGrpc.java
  proto-google-cloud-billingbudgets-v1beta1/clirr-ignored-differences.xml
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/BudgetModel.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/Filter.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/FilterOrBuilder.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/proto/google/cloud/billing/budgets/v1beta1/budget_model.proto
  proto-google-cloud-billingbudgets-v1beta1/src/main/proto/google/cloud/billing/budgets/v1beta1/budget_service.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#166 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: cla: yes, context: full

#168 chore: regenerate with updated protoc
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/AllUpdatesRule.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/Budget.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/BudgetAmount.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/CreateBudgetRequest.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/DeleteBudgetRequest.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/Filter.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/GetBudgetRequest.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/ListBudgetsRequest.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/ListBudgetsResponse.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/ThresholdRule.java
  proto-google-cloud-billingbudgets-v1beta1/src/main/java/com/google/cloud/billing/budgets/v1beta1/UpdateBudgetRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#170 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#172 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#177 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#181 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#182 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-billingbudgets/pom.xml
  grpc-google-cloud-billingbudgets-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-billingbudgets-v1beta1/pom.xml
Labels: cla: yes

#186 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#194 fix: migrate to grpc_service_config
  README.md
  google-cloud-billingbudgets/src/main/java/com/google/cloud/billing/budgets/v1beta1/stub/BudgetServiceStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#199 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
