Repository googleapis/java-billingbudgets, pull requests merged in 2021-05, with the labels that each got.

#462 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: none

#463 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: billingbudgets, automerge, cla: yes

#464 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#471 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#472 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#474 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#475 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#477 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full

#483 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: billingbudgets, automerge, cla: yes

#480 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: billingbudgets, automerge, cla: yes, context: full
